-- Emits shared/db/permissions.snapshot.md by querying pg_catalog
-- introspection sources for the live `public` schema. Driven by
-- scripts/db/gen-permissions-snapshot.cjs (which runs this file via
-- `docker exec ... psql` against the local Supabase stack and
-- redirects stdout to the snapshot path).
--
-- Determinism contract (CCI-2): two consecutive runs against the
-- same DB state must produce byte-identical output. To hold that,
-- every query below is ORDER BY'd on a stable key set and emits no
-- environment-derived content (no timestamps, no DB URLs, no
-- container names). All formatting whitespace in policy quals and
-- function arg lists is normalized via regexp_replace.
--
-- Coverage contract (CCI-1): the inventory iterated below matches
-- the public:Tables, public:Views, and public:Functions blocks in
-- shared/db/types.ts (Supabase-CLI generated). Trigger functions are
-- excluded (prorettype = trigger) because they are internal
-- machinery rather than callable API surface, matching types.ts.
--
-- Privileges contract: tables and views report the full SQL-standard
-- grantable set (SELECT, INSERT, UPDATE, DELETE, TRUNCATE,
-- REFERENCES, TRIGGER). Functions report EXECUTE. Per-role coverage
-- spans anon, authenticated, service_role, and the PUBLIC
-- pseudo-role.

\pset format unaligned
\pset tuples_only on
\pset border 0
\pset footer off
\pset null ''
\pset recordsep '\n'
\pset fieldsep ''

set client_min_messages = warning;
set search_path = pg_catalog;

create or replace function pg_temp.normalize_ws(t text) returns text as $$
  select trim(regexp_replace(coalesce(t, ''), '\s+', ' ', 'g'))
$$ language sql immutable;

create or replace function pg_temp.role_csv(
  oid_in oid,
  kind text  -- 'table' or 'function'
) returns text as $$
declare
  roles text[] := array['anon', 'authenticated', 'service_role', 'public'];
  privs text[] := case
    when kind = 'function' then array['EXECUTE']
    else array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']
  end;
begin
  -- unused helper retained for clarity in the file; per-privilege
  -- formatting is inlined below for readability.
  return null;
end;
$$ language plpgsql immutable;

create or replace function pg_temp.emit_snapshot() returns setof text as $$
declare
  roles_in_scope text[] := array['anon', 'authenticated', 'service_role', 'public'];
  relation_privs text[] := array[
    'SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'
  ];
  r record;
  priv text;
  granted text;
  policy_row record;
  policy_count int;
  func_row record;
  exec_csv text;
begin
  -- ── Header ────────────────────────────────────────────────────
  return next '# Database Permissions Snapshot';
  return next '';
  return next '<!--';
  return next '  Generated by `npm run db:gen-permissions`. Do not edit by';
  return next '  hand; manual changes are erased on regeneration. The';
  return next '  generator is `scripts/db/gen-permissions-snapshot.cjs`,';
  return next '  which executes `scripts/db/permissions-snapshot.sql`';
  return next '  against the local Supabase stack.';
  return next '-->';
  return next '';
  return next 'A per-object snapshot of the live `public` schema''s permissions';
  return next 'posture at the migration set checked into this repo. Sibling to';
  return next '[`shared/db/types.ts`](./types.ts) (row shapes); the two together';
  return next 'are the in-repo answer to "what is true for `public.X` today."';
  return next '';
  return next '## Roles in scope';
  return next '';
  return next 'Per-role coverage spans `anon`, `authenticated`, `service_role`,';
  return next 'and the `PUBLIC` pseudo-role. Privileges granted to `PUBLIC`';
  return next 'reach every role (including `anon` and `authenticated`). The';
  return next '`postgres` owner role is implicit — owners hold every privilege';
  return next 'on objects they own.';
  return next '';
  return next '## Privileges in scope';
  return next '';
  return next 'Tables and views: the SQL-standard grantable set — `SELECT`,';
  return next '`INSERT`, `UPDATE`, `DELETE`, `TRUNCATE`, `REFERENCES`, `TRIGGER`.';
  return next 'Functions: `EXECUTE`.';
  return next '';

  -- ── Tables ────────────────────────────────────────────────────
  return next '## Tables';
  for r in
    select c.oid, c.relname, c.relrowsecurity
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r'
    order by c.relname
  loop
    return next '';
    return next '### `' || r.relname || '`';
    return next '';
    return next '- RLS: ' || case when r.relrowsecurity then 'enabled' else 'disabled' end;
    return next '- Grants:';
    foreach priv in array relation_privs loop
      select string_agg(role_name, ', ' order by role_name)
        into granted
        from unnest(roles_in_scope) as role_name
        where has_table_privilege(role_name, r.oid, priv);
      return next '  - `' || priv || '`: ' || coalesce(granted, '(none)');
    end loop;
    select count(*) into policy_count from pg_policies
      where schemaname = 'public' and tablename = r.relname;
    if policy_count = 0 then
      return next '- Policies: (none)';
    else
      return next '- Policies:';
      for policy_row in
        select policyname, cmd, roles, qual, with_check
        from pg_policies
        where schemaname = 'public' and tablename = r.relname
        order by policyname
      loop
        return next '  - `' || policy_row.policyname || '` ('
          || 'FOR `' || policy_row.cmd || '` TO '
          || array_to_string(
               (select array_agg('`' || rn || '`' order by rn)
                from unnest(policy_row.roles) as rn),
               ', ')
          || ')';
        return next '    - USING: '
          || case when policy_row.qual is null or policy_row.qual = ''
                  then '(none)'
                  else '`' || pg_temp.normalize_ws(policy_row.qual) || '`'
             end;
        return next '    - WITH CHECK: '
          || case when policy_row.with_check is null or policy_row.with_check = ''
                  then '(none)'
                  else '`' || pg_temp.normalize_ws(policy_row.with_check) || '`'
             end;
      end loop;
    end if;
  end loop;
  return next '';

  -- ── Views ─────────────────────────────────────────────────────
  return next '## Views';
  for r in
    select c.oid, c.relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'v'
    order by c.relname
  loop
    return next '';
    return next '### `' || r.relname || '`';
    return next '';
    return next '- Grants:';
    foreach priv in array relation_privs loop
      select string_agg(role_name, ', ' order by role_name)
        into granted
        from unnest(roles_in_scope) as role_name
        where has_table_privilege(role_name, r.oid, priv);
      return next '  - `' || priv || '`: ' || coalesce(granted, '(none)');
    end loop;
  end loop;
  return next '';

  -- ── Functions ─────────────────────────────────────────────────
  return next '## Functions';
  for func_row in
    select p.oid,
           p.proname,
           pg_get_function_identity_arguments(p.oid) as args,
           p.prosecdef,
           pg_get_function_result(p.oid) as result
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prokind = 'f'
      and p.prorettype <> 'pg_catalog.trigger'::regtype
    order by p.proname, pg_get_function_identity_arguments(p.oid)
  loop
    return next '';
    return next '### `' || func_row.proname || '(' || func_row.args || ')`';
    return next '';
    return next '- Returns: `' || pg_temp.normalize_ws(func_row.result) || '`';
    return next '- SECURITY: ' || case when func_row.prosecdef then 'DEFINER' else 'INVOKER' end;
    select string_agg(role_name, ', ' order by role_name)
      into exec_csv
      from unnest(roles_in_scope) as role_name
      where has_function_privilege(role_name, func_row.oid, 'EXECUTE');
    return next '- `EXECUTE`: ' || coalesce(exec_csv, '(none)');
  end loop;
  return next '';
end;
$$ language plpgsql;

select pg_temp.emit_snapshot();
